# This is a basic workflow to build robot code.

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on: [push, pull_request]

jobs:
  # JOB to run change detection
  #check-changes:
  #  runs-on: ubuntu-latest
    # Set job outputs to values from filter step
  #  outputs:
  #    build: ${{ steps.filter.outputs.build }}
  #  steps:
    # For pull requests it's not necessary to checkout the code
  #  - uses: dorny/paths-filter@v2
  #    id: filter
  #    with:
  #      filters: |
  #        build:
  #          - 'src/**'

  # JOB to build and test build code
  build:
    #needs: check-changes
    #if: ${{ needs.changes.outputs.build == 'true' }}
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2022-20.04

    # Build the code
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        run: ./gradlew build